Update docker-image.yml
bump_type:major

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -15,13 +15,12 @@ jobs:
         uses: actions/checkout@v2
         continue-on-error: false
 
-      - name: Configure AWS credentials
+      - name: Configure AWS credentials using OIDC
         uses: aws-actions/configure-aws-credentials@v1
-        with: 
+        with:
           role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
           aws-region: ${{ secrets.AWS_REGION }}
-        continue-on-error: false
-        
+
       - name: Verify AWS credentials
         run: aws sts get-caller-identity
 
@@ -29,9 +28,10 @@ jobs:
         id: login-ecr
         run: |
           aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
-          if [$? -ne 0]; then
+          if [ $? -ne 0 ]; then
             echo "ECR login failed" && exit 1
           fi
+
       - name: Determine new image tag
         id: versioning
         run: |
@@ -70,14 +70,15 @@ jobs:
         run: |
             IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$NEW_TAG
             docker build -t $IMAGE_URI .
-            if [$? -ne 0]; then
+            if [ $? -ne 0 ]; then
               echo "Docker build failed" && exit 1
             fi
             docker push $IMAGE_URI
-            if [$? -ne 0]; then
+            if [ $? -ne 0 ]; then
               echo "Docker push failed" && exit 1
             fi
             echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
+
       - name: Register a new ECS Task Definition Revision
         id: register-task-def
         env:
@@ -89,24 +90,22 @@ jobs:
             --task-definition ui \
             --query taskDefinition \
             --output json)
-          if [$? -ne 0]; then
-            echo "Failed to fetch the existing the task defination" && exit 1
+          if [ $? -ne 0 ]; then
+            echo "Failed to fetch the existing task definition" && exit 1
           fi
-  
 
           # Create a new task definition with the updated image
           UPDATED_TASK_DEF=$(echo $EXISTING_TASK_DEF | jq --arg IMAGE_URI "$IMAGE_URI" '.containerDefinitions[0].image = $IMAGE_URI')
-          if [$? -ne 0]; then
-            echo "Failed to update task defination" && exit 1
+          if [ $? -ne 0 ]; then
+            echo "Failed to update task definition" && exit 1
           fi 
 
           # Register the new task definition revision
           echo $UPDATED_TASK_DEF | jq 'del(.status, .revision, .taskDefinitionArn, .registeredAt, .registeredBy)' > new-task-def.json
           aws ecs register-task-definition --cli-input-json file://new-task-def.json
-          if [$? -ne 0]; then
-            echo "Failed to regester the task defination" && exit 1
+          if [ $? -ne 0 ]; then
+            echo "Failed to register the task definition" && exit 1
           fi
-  
 
       - name: Deploy to ECS Frontend Service
         env:
@@ -116,8 +115,8 @@ jobs:
         run: |
           # Get the latest revision of the task definition
           NEW_TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition ui --query 'taskDefinition.taskDefinitionArn' --output text)
-          if [$? -ne 0]; then
-            echo "Failed to retirve the task defination ARN" && exit 1
+          if [ $? -ne 0 ]; then
+            echo "Failed to retrieve the task definition ARN" && exit 1
           fi
           # Update the service with the new task definition
           aws ecs update-service \
@@ -125,6 +124,6 @@ jobs:
             --service $ECS_SERVICE \
             --task-definition $NEW_TASK_DEF_ARN \
             --force-new-deployment
-          if [$? -ne 0]; then
-            echo "failed to update the service" && exit 1
+          if [ $? -ne 0 ]; then
+            echo "Failed to update the service" && exit 1
           fi
